sudo: false

os: linux
dist: xenial

language: python

python: 3.7

addons:
  apt:
    packages:
      - libarchive-dev
      - libssl-dev
      - ninja-build
      - tree

install:
  - pip install meson
  - wget https://github.com/idiv-biodiversity/archive-sum/archive/v1.1.1.tar.gz
  - tar xzf v1.1.1.tar.gz
  - meson --prefix="$HOME" archive-sum-1.1.1/build archive-sum-1.1.1
  - ninja -C archive-sum-1.1.1/build install

script:
  - make check
  - make VERBOSE=yes test

cache: pip
